version: 2

seeds:
  - name: hcp_master
    description: >
      Healthcare Provider (HCP) master data containing information about healthcare
      providers including their specialties, locations, and potential scores.
      This is the primary source of truth for healthcare provider information.
    columns:
      - name: hcp_id
        description: Unique identifier for the healthcare provider
        tests:
          - unique
          - not_null
      - name: first_name
        description: First name of the healthcare provider
      - name: last_name
        description: Last name of the healthcare provider
      - name: specialty
        description: Medical specialty of the healthcare provider (e.g., Cardiologist, Pediatrician)
      - name: facility
        description: Type of facility where the healthcare provider practices (e.g., Hospital, Clinic)
      - name: years_of_practice
        description: Number of years the healthcare provider has been practicing medicine
        data_type: integer
      - name: state
        description: US state abbreviation where the healthcare provider is located
      - name: city
        description: City where the healthcare provider is located
      - name: zip_code
        description: ZIP code of the healthcare provider's practice location
      - name: email
        description: Email address of the healthcare provider
      - name: phone
        description: Phone number of the healthcare provider
      - name: territory_id
        description: Territory ID the healthcare provider belongs to for sales organization purposes
      - name: potential_score
        description: Score representing the prescription potential of the healthcare provider (range 1-100)
        data_type: integer
      - name: influence_score
        description: Score representing the healthcare provider's influence in their field (range 1-10)
        data_type: integer
      - name: created_at
        description: Date when the healthcare provider record was created in the system
        data_type: date 