name: 'airflow_dbt_snowflake'
version: '1.0.0'
config-version: 2

profile: 'snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  airflow_dbt_snowflake:
    +enabled: true
    hcp_master:
      +column_types:
        years_of_practice: integer
        potential_score: integer
        influence_score: integer
        created_at: date

models:
  airflow_dbt_snowflake:
    materialized: table