version: 2

models:
  - name: fct_visits
    description: "Fact table for HCP visits with aggregated metrics and dimensions"
    columns:
      - name: visit_id
        description: "Unique identifier for the visit"
        tests:
          - unique
          - not_null
      - name: visit_date
        description: "Date when the visit occurred"
      - name: visit_year
        description: "Year of the visit"
      - name: visit_month
        description: "Month of the visit (1-12)"
      - name: visit_quarter
        description: "Quarter of the visit (1-4)"
      - name: visit_type
        description: "Type of visit (In-person, Virtual, Phone call)"
      - name: duration_minutes
        description: "Duration of the visit in minutes"
      - name: outcome
        description: "Outcome of the visit (Very Positive, Positive, Neutral, Negative, Very Negative)"
      - name: engagement_score
        description: "Engagement score of the visit (0-10)"
      - name: products_discussed
        description: "List of products discussed during the visit (comma-separated)"
      - name: hcp_id
        description: "Healthcare professional identifier"
      - name: hcp_full_name
        description: "Full name of the healthcare professional"
      - name: hcp_specialty
        description: "Medical specialty of the healthcare professional"
      - name: hcp_facility
        description: "Type of facility where the healthcare professional works"
      - name: hcp_territory_id
        description: "Territory to which the healthcare professional belongs"
      - name: mr_id
        description: "Medical representative identifier"
      - name: mr_full_name
        description: "Full name of the medical representative"
      - name: mr_territory_ids
        description: "Territories assigned to the medical representative (comma-separated)"
      - name: is_positive_outcome
        description: "Flag indicating if the visit outcome was positive (1) or not (0)"
      - name: is_negative_outcome
        description: "Flag indicating if the visit outcome was negative (1) or not (0)"
      - name: is_high_engagement
        description: "Flag indicating if the engagement score was high (>=7)"

  - name: fct_prescriptions
    description: "Fact table for prescriptions with revenue metrics"
    columns:
      - name: year_month
        description: "Year and month of the prescription (YYYY-MM)"
      - name: prescription_year
        description: "Year of the prescription"
      - name: prescription_month
        description: "Month of the prescription (1-12)"
      - name: hcp_id
        description: "Healthcare professional identifier"
      - name: hcp_full_name
        description: "Full name of the healthcare professional"
      - name: hcp_specialty
        description: "Medical specialty of the healthcare professional"
      - name: hcp_territory_id
        description: "Territory to which the healthcare professional belongs"
      - name: product
        description: "Name of the product prescribed"
      - name: product_id
        description: "Unique identifier for the product"
      - name: therapeutic_area
        description: "Therapeutic area of the product"
      - name: territory_name
        description: "Name of the territory where the HCP is located"
      - name: region
        description: "Region where the HCP's territory is located"
      - name: num_prescriptions
        description: "Number of prescriptions made in the given month"
      - name: total_units
        description: "Total units prescribed in the given month"
      - name: price_per_unit
        description: "Price per unit of the product in dollars"
      - name: estimated_revenue
        description: "Estimated revenue generated from this prescription (total_units * price_per_unit)"
      - name: annual_revenue_target
        description: "Annual revenue target for the product in dollars"
      - name: revenue_target_percentage
        description: "Percentage of revenue target achieved by this prescription"

  - name: dim_hcp
    description: "Dimension table for Healthcare Professionals with segmentation"
    columns:
      - name: hcp_id
        description: "Unique identifier for the healthcare professional"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the healthcare professional"
      - name: last_name
        description: "Last name of the healthcare professional"
      - name: full_name
        description: "Full name of the healthcare professional"
      - name: specialty
        description: "Medical specialty of the healthcare professional"
      - name: facility
        description: "Type of facility where the healthcare professional works"
      - name: years_of_practice
        description: "Number of years the healthcare professional has been in practice"
      - name: email
        description: "Email address of the healthcare professional"
      - name: phone
        description: "Phone number of the healthcare professional"
      - name: state
        description: "State where the healthcare professional practices"
      - name: city
        description: "City where the healthcare professional practices"
      - name: zip_code
        description: "ZIP code of the healthcare professional's location"
      - name: territory_id
        description: "Territory to which the healthcare professional belongs"
      - name: territory_name
        description: "Name of the territory where the HCP is located"
      - name: region
        description: "Region where the HCP's territory is located"
      - name: territory_states
        description: "States included in the HCP's territory"
      - name: territory_potential_value
        description: "Potential market value of the HCP's territory in dollars"
      - name: potential_score
        description: "Potential value score of the healthcare professional (0-100)"
      - name: influence_score
        description: "Influence score of the healthcare professional (0-10)"
      - name: created_at
        description: "Date when the healthcare professional record was created"
      - name: potential_category
        description: "Category of potential value (High, Medium, Low)"
      - name: influence_category
        description: "Category of influence (High, Medium, Low)"
      - name: hcp_segment
        description: "Segmentation of the HCP (Key Target, Priority, Standard)" 